- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch ubuntu
      os_server:
        image: ubuntu
        name: drkarim
        availability_zone: nova
        flavor: std.2
        state: present
        network: INTNET
