- name: Launch a compute instance
  hosts: localhost
  tasks:
    - name: Launch Centos 7
      os_server:
        image: CentOS7
        name: vm1
        availability_zone: nova
        flavor: std.1
        state: present
        network: INTNET
